### ISSUE TITLE
Unexpected Token: ...

### ISSUE THREAD

**Issue by concon121** [mikestead/bitbucket-changelog#2]
I'm getting an unexpected token on the spread syntax you're using.

```
$ bbgenlog -i
C:\Users\ConnorB\AppData\Roaming\npm\node_modules\bitbucket-changelog\index.js:264
        const jiras = [ ...new Set(comb) ]
                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

Some details about my set up:
```
$ node --version
v4.5.0
$ npm --version
4.3.0
```

**Comment by mikestead** [comment]
Missed this one sorry. You'll need to use a more recent version of Node. 6+ should be fine.
